spring.application.name=GeoTask

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/geotask
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis??
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=org.syj.geotask.task.entity
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# Dify Configuration
dify.base-url=http://127.0.0.1/v1
dify.app-api-key=app-64jqmIYqUWG8gjqkV0iYj90q
dify.dataset-api-key=
dify.default-user-id=default-user
dify.connect-timeout=30000
dify.read-timeout=60000
dify.retry-enabled=true
dify.max-retries=3
dify.retry-interval=1000
